seed_everything: 42
data:
  task: lane
model:
  task: lane
  class_weights_path: cache/class_weights_lane.json
  model:
    class_path: skyscapesnet.models.baselines.AdapNet
    init_args:
      n_classes: 13
      output_stride: 8
      bottleneck_channels: 512
      n_multiscale_blocks: 4
      atrous_rates: [1, 2, 3]
  loss:
    class_path: skyscapesnet.losses.loss.SegLoss
    init_args:
      n_classes: 13
