seed_everything: 42
data:
  task: dense
model:
  task: dense
  class_weights_path: cache/class_weights_dense.json
  model:
    class_path: skyscapesnet.models.baselines.GCN
    init_args:
      n_classes: 20
      kernel_size: 15
  loss:
    class_path: skyscapesnet.losses.loss.SegLoss
    init_args:
      n_classes: 20
