seed_everything: 42
data:
  task: lane
model:
  task: lane
  class_weights_path: cache/class_weights_lane.json
  model:
    class_path: skyscapesnet.models.baselines.RefineNet
    init_args:
      n_classes: 13
      channels: 256
  loss:
    class_path: skyscapesnet.losses.loss.SegLoss
    init_args:
      n_classes: 13
