seed_everything: 42
data:
  task: dense
model:
  task: dense
  class_weights_path: cache/class_weights_dense.json
  model:
    class_path: skyscapesnet.models.baselines.UNet
    init_args:
      n_classes: 20
      base_channels: 64
      bilinear: true
  loss:
    class_path: skyscapesnet.losses.loss.SegLoss
    init_args:
      n_classes: 20
